from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import requests
import re
from bs4 import BeautifulSoup
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
import io

app = Flask(__name__)
CORS(app)  # Allows your frontend dashboard to communicate with this server

def perform_seo_audit(url):
    """Analyzes the HTML of a store to find common SEO issues"""
    try:
        # Adding a user-agent to avoid being blocked by stores
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        response = requests.get(url, timeout=10, headers=headers)
        soup = BeautifulSoup(response.text, 'html.parser')
        
        score = 100
        issues = []
        
        # Check for H1 Header
        if not soup.find('h1'):
            score -= 20
            issues.append("Missing H1 Header (Critical for SEO)")
        
        # Check for Meta Description
        if not soup.find('meta', attrs={'name': 'description'}):
            score -= 20
            issues.append("Missing Meta Description")

        # Check for Image Alt Tags
        images = soup.find_all('img')
        if images and not any(img.get('alt') for img in images):
            score -= 10
            issues.append("Images missing Alt text")
        
        return score, issues
    except Exception as e:
        return 50, [f"Could not reach site: {str(e)}"]

@app.route('/api/scan', methods=['POST'])
def scan():
    """Endpoint to find leads based on niche and country"""
    data = request.json
    niche = data.get('niche', 'skincare')
    country = data.get('country', 'USA')
    
    # In production, this would use a search engine scraper
    # For now, we provide a structured mock response that follows your UI requirements
    mock_leads = [
        {
            "name": f"{niche.capitalize()} Elite Store",
            "url": "https://example-store-1.com",
            "email": f"info@{niche.lower()}store.com",
            "seo_score": 82,
            "niche": niche,
            "country": country
        },
        {
            "name": f"Global {niche.capitalize()} Co",
            "url": "https://example-store-2.com",
            "email": f"support@{niche.lower()}global.com",
            "seo_score": 64,
            "niche": niche,
            "country": country
        }
    ]
    return jsonify(mock_leads)

@app.route('/api/generate-pdf', methods=['POST'])
def generate_pdf():
    """Generates a professional PDF audit report for a specific lead"""
    lead = request.json
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    
    # PDF Styling
    p.setFont("Helvetica-Bold", 18)
    p.drawString(100, 750, "SHOPIFY LEAD GENIUS - SEO AUDIT")
    
    p.setStrokeColorRGB(0.2, 0.4, 0.8)
    p.line(100, 740, 500, 740)
    
    p.setFont("Helvetica-Bold", 12)
    p.drawString(100, 710, f"Business Name: {lead['name']}")
    p.setFont("Helvetica", 12)
    p.drawString(100, 690, f"Website: {lead['url']}")
    p.drawString(100, 670, f"Contact Email: {lead['email']}")
    
    # SEO Score Section
    p.setFont("Helvetica-Bold", 14)
    p.drawString(100, 630, f"SEO Health Score: {lead['seo_score']}/100")
    
    p.setFont("Helvetica", 10)
    p.drawString(100, 610, "Status: Improvements Recommended")
    
    p.setFont("Helvetica-Oblique", 9)
    p.drawString(100, 100, "Generated by ShopifyLeadGenius - Confidential Audit Report")
    
    p.showPage()
    p.save()
    
    buffer.seek(0)
    return send_file(
        buffer, 
        as_attachment=True, 
        download_name=f"Audit_{lead['name'].replace(' ', '_')}.pdf", 
        mimetype='application/pdf'
    )

if __name__ == '__main__':
    # Running on port 5000 as expected by the React frontend
    app.run(port=5000, debug=True)
